In [2]:
import numpy as Lp
from scipy.sparse import diags
from scipy.sparse import csr_array
from scipy.sparse import linalg
import math

import matplotlib.pyplot as plt

# Pre

In [47]:

class SimulationGrid:

    def __init__(self, L, _type = 'Square'):
        """

        Creates a simulation grid.

        Inputs:

            - L: Square size, rectangle shape or circle diameter. Without considering boundaries
        """
        self.L = L
        self.initialize(_type)
        self.data = [] #For simulations

    def initialize(self,  _type):
        """
        Initializes the v vector and M matrix in function of the type of grid
        """
        if _type == 'Square':
            self.M_sq = self.m_square()
        elif _type == 'Rectangle':
            self.M_rc = self.m_rectangle()
        elif _type == 'Circle':
            self.M_ci = self.m_circle()
        else:
            print("That does not work")
        self.eigenvalues, self.eigenvectors = np.linalg.eig(self.M)
        self.eigenfrequencies = np.sqrt(np.abs(self.eigenvalues))

    def m_square(self):
        """
        Considers the grid as a square of size N
        """
        n = self.L**2

        x_diag = np.ones(n-1)
        x_diag[np.arange(1,n) % self.L == 0] = 0
        y_diag = np.ones(n- self.L)

        d = [y_diag, x_diag, np.full(n,-4), x_diag, y_diag]
        return M = diags(d , [-self.L,-1,0,1,self.L]).toarray()
 
        
    def m_rectangle(self, m = 2):
        """
        Considers the grid as a rectangle of heigh of N and length 2*N
        Inputs:
            - m: Scale from L for Y axis
        """
        n = self.L*self.L*m

        x_diag = np.ones(n-1)
        x_diag[np.arange(1,n) % self.L == 0] = 0

        y_diag = np.ones(n - self.L*m)

        d = [y_diag, x_diag, np.full(n,-4), x_diag, y_diag]

        return M = diags(d , [-self.L*m,-1,0,1,self.L*m]).toarray()

        
    def m_circle(self):
        """
        Considers the grid as a circle of diameter N
        """
        M = self.square()
        center = [self.L/2, self.L/2]
        not_circle = np.abs(np.indices(matrix.shape) - center[:, np.newaxis, np.newaxis])

        
        


    
    def animation(self,save_animation = False):
        """

        Animates the stepping scheme:

        Inputs:

            -   method: If using time_dependent or time_independent

            -   save_animation: True == it will save the animation, default is False
        """

        fig, ax = plt.subplots()       

        C = np.copy(self.data)


        C = np.copy(self.A)
        

        ax.imshow(C, cmap='hot', interpolation='nearest', extent=[0, 1, 0, 1])

        ax.set_xlabel('X')  

        ax.set_ylabel('Y')  

        ax.set_title('Time: 0 s') 
        

        anim = animation.FuncAnimation(fig,self.frame, fargs= (ax,), frames=int(n_steps), interval = 0.000000001)


        if save_animation == True:

            print("Starting ")

            anim.save('time_dependent_diffusion_animation.mp4', fps=60)
            plt.close()

    def frame(self, iteration, ax):

        C = self.data[iteration]

        ax.clear()

        ax.set_title(f'Time dependent(t={np.round(iteration*0.0001*50, 7)}) s')

        ax.imshow(C, cmap='hot', interpolation='nearest', extent=[0, 1, 0, 1])


# Part I

## A

Done

## B

In [49]:
L = 3
square = SimulationGrid(L, _type = 'Square')
print(square.M)
rectangle = SimulationGrid(L, _type = 'Rectangle')
print(rectangle.M)
circle = SimulationGrid(L, _type = 'Circle')

[[-4.  1.  0.  1.  0.  0.  0.  0.  0.]
 [ 1. -4.  1.  0.  1.  0.  0.  0.  0.]
 [ 0.  1. -4.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0. -4.  1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1. -4.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  1. -4.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.  0. -4.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  1. -4.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  1. -4.]]
[[-4.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -4.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -4.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -4.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -4.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -4.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0. -4.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  1. -4.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  1. -4.  0.  0.  0

IndexError: arrays used as indices must be of integer (or boolean) type